### ISSUE TITLE
测试报告-1642-C++ 进阶应用实战

### ISSUE THREAD

**Issue by huhuhang** [huhuhang/courses-test-report#4]
### 测试说明（请仔细阅读）

- 测试课程主要涉及三个方面问题：代码是否能正常运行，语句是否通顺，错别字和错用标点符号。
- 请务必在线上环境中按步骤学习，并测试课程中的代码执行情况，而非本地环境。
- 每个课程根据内容量不同，如无法按约定时间完成课程测试，请及时告知与你对接的实验楼同事，以便于我们协调课程测试进度。

我们会在实验文档中故意设置几处埋点错误，仅限于明显的错别字及描述语病，测试人员需要全部修复才算完成测试。未按时完成或未找到全部埋点错误的用户，将不能获得测试奖励。增加埋点错误并不是给各位同学增加获取福利的难度，而是希望各位参与测试的同学可以认真对待本次测试。**由于测试课程未正式上线，请不要在任何渠道泄露或公开内容。**

### 报告示例

测试过程中，请在此 issues 下方以评论的方式记录问题（如下示例，评论可反复补充编辑）。请使用编辑器提供的任务列表样式，将单独的问题列出来。

报告补充示例：https://github.com/huhuhang/courses-test-report/issues/1

### 测试课程

- 课程线上地址：LAB-1642
- 关联内部任务：https://github.com/sjtushi/lab/issues/408

**Comment by 2000andre** [comment]
![image](https://user-images.githubusercontent.com/42809789/83761875-77ee2100-a6a9-11ea-9b04-5b9f0a6ac346.png)
初识类和对象中的示例代码 1少缺少包含头文件<string>无法编译通过，需要加上头文件

**Comment by 2000andre** [comment]
![image](https://user-images.githubusercontent.com/42809789/83765850-43309880-a6ae-11ea-962e-17dfe9a45a56.png)
文档有误，在初识类和对象的实验操作2中，因为使用了c++11中的东西，编译时候需要加上-std=c++11，否则无法编译通过

**Comment by 2000andre** [comment]
![image](https://user-images.githubusercontent.com/42809789/83829188-db616880-a714-11ea-8968-6cd0e4492bcd.png)
初识类和对象中的示例代码5 中定义的内联函数的代码错误，因为没有返回值，编译会报错

**Comment by 2000andre** [comment]
![image](https://user-images.githubusercontent.com/42809789/83829936-a0603480-a716-11ea-9041-c187feece32f.png)
函数体不应该以分号结尾

**Comment by 2000andre** [comment]
@huhuhang 请问以这种方式反馈方面楼楼矫正吗？

**Comment by 2000andre** [comment]
![image](https://user-images.githubusercontent.com/42809789/83844170-05c51d00-a739-11ea-9a1b-c1a05ccf236f.png)
这段代码中，使用了标准库中的string，但是并未包含<string>头文件，并且需要开放标准命名空间作为示例代码会编译报错

**Comment by huhuhang** [comment]
> @huhuhang 请问以这种方式反馈（截图+文字描述）方便楼楼矫正吗？

可以的，作者会处理，处理之后会直接标记。

**Comment by 2000andre** [comment]
![image](https://user-images.githubusercontent.com/42809789/83855589-e1723c00-a74a-11ea-8b1e-2e7e8d09b1ed.png)
按照代码示例敲完报错，需要加入头文件<iostream>使用标准命名空间

**Comment by 2000andre** [comment]
![image](https://user-images.githubusercontent.com/42809789/83858462-20a28c00-a74f-11ea-994f-bb43b30d9599.png)
缺少<iostream>头文件，没有使用标准命名空间，示例中代码直接编辑会报错

**Comment by 2000andre** [comment]
![image](https://user-images.githubusercontent.com/42809789/83861115-c5729880-a752-11ea-8e9d-26b87b5c918d.png)
文档书写错误，应该是也称为对象指针

**Comment by 2000andre** [comment]
@huhuhang 发现了一个问题，所用测试用例代码中，都没有包含该有头文件，如果部分楼粉的基础不好，就会发现所有代码都会报错，并不能看着敲一遍直接运行

**Comment by LJJ931026** [comment]
> ![image](https://user-images.githubusercontent.com/42809789/83844170-05c51d00-a739-11ea-9a1b-c1a05ccf236f.png)
> 这段代码中，使用了标准库中的string，但是并未包含头文件，并且需要开放标准命名空间作为示例代码会编译报错

之前为了避免示例代码看起来比较赘余，在后面的示例代码中都没有加上头文件。

**Comment by LJJ931026** [comment]
> * [ ]  发现了一个问题，所用测试用例代码中，都没有包含该有头文件，如果部分楼粉的基础不好，就会发现所有代码都会报错，并不能看着敲一遍直接运行

之前为了避免示例代码看起来比较赘余，在后面的示例代码中都没有加上头文件。
我会在 review 的时候后面统一加上头文件，以及编译参数 -std=c++11。

**Comment by 2000andre** [comment]
![image](https://user-images.githubusercontent.com/42809789/83965502-bd4b6200-a8e6-11ea-8183-4a5dfa3b3991.png)
示例代码有错我，没有对构造函数设置public访问权限，无法产生对象，如果编写实例化对象的代码会报错，析构函数也不会生效

**Comment by 2000andre** [comment]
@huhuhang 我这里结束了，代码都已经跑了一遍，但是能力有限，多态那一章节，弄得不是很明白

**Comment by huhuhang** [comment]
> @huhuhang 我这里结束了，代码都已经跑了一遍，但是能力有限，多态那一章节，弄得不是很明白

感谢参与测试。🙏
